num1 = int(input("Primeiro número: "))
num2 = int(input("Segundo número: "))
print("Soma: ", {num1 + num2})
print("Diferença: ", {num1 - num2})
print("Multiplicação: ", {num1 * num2})
print("Divisão: ", {num1/ num2})
